### ISSUE TITLE
qrz - add link on callsign to QRZ page

### ISSUE THREAD

**Issue by brianjester** [brianjester/brianjester.github.com#10]
As a user, I would like to search for a contact, then when their callsign appears, I would like it to be a clickable link to their QRZ page.

Submitted by Glenn sims (FB)

**Comment by simsnet** [comment]
That is me

**Comment by simsnet** [comment]
Hey Brian, check out my PR #12 and see what you think.  I'm not the best at JS so you might have a better way to approach this, but this fits inside your code seamlessly.

[Live demo for the moment](https://data.glennjam.in/qrz)

**Comment by brianjester** [comment]
Got it, I pulled in the commit to create the link and open in a new tab, thank you!
