### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bmitch** [brianjester/brianjester.github.com#24]
Just wanted to say thank you for this tool. Found it tonight and used it. Is great!

**Comment by brianjester** [comment]
@bmitch That's great to hear, which tool?

- [IndexFlip](http://indexflip.com/) - Flashcards for Japanese Kanji and Hiragana, Amateur Radio Technician question pool, DMV practice tests, and Real Estate practice tests.
- [DMR QRZ](http://dmrqrz.com/) - Lookup contacts in the DMR DB by ID or call sign
- [Cabrillo Logs](http://cabrillolog.com/) - cCreate your Amateur Radio contest log here.
- [SOTA Log](http://sotalogs.com/) - Easy CSV SOTA Logs
- [Castles of Okinawa](https://brianjester.github.io/okinawa-castles/index.html) - 12 castles you won't want to miss!
- [Fun Filipino Words and Culture](https://a.co/d/4WbDkpE) - check out our book on Amazon
- [Unofficial Anytone Radio Site](https://brianjester.github.io/anytone) - Everything you'll need to setup your new DMR radio.
- [Passive Income Projects](https://brianjester.github.io/passive-income) - Here's our chart of passive income from our side projects.
- [Morse Code Key](https://brianjester.github.io/morse) - In-browser Morse code key, for use on PC with mouse.

**Comment by bmitch** [comment]
Oh didn't realise this repo contained many :) It is the SOTA Log too. I'll check the other ones out now!

**Comment by brianjester** [comment]
I actually had a couple folks think it odd that I didn't want to enter them one by one on the sota database web form, but I just found it easier & faster to create my own "file" then copy & paste it all at once. 73, Brian/kb8uip/ve3spg/cg3spg

**Comment by bmitch** [comment]
I have been frustrated with the SOTA form before and have accidentally lost each entry I've made one by one.

Your tool solves that though :)
